/*
 * This file is generated by jOOQ.
*/
package com.springboot.sources;


import com.springboot.sources.routines.PostProcedure;

import javax.annotation.Generated;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>jooq.post_procedure</code>
     */
    public static Integer postProcedure(Configuration configuration, String title) {
        PostProcedure p = new PostProcedure();
        p.setTitle(title);

        p.execute(configuration);
        return p.getPostCount();
    }
}
