/*
 * This file is generated by jOOQ.
*/
package com.springboot.sources;


import com.springboot.sources.tables.FlywaySchemaHistory;
import com.springboot.sources.tables.Post;
import com.springboot.sources.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.springboot.sources.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jooq.post</code>.
     */
    public static final Post POST = com.springboot.sources.tables.Post.POST;

    /**
     * The table <code>jooq.user</code>.
     */
    public static final User USER = com.springboot.sources.tables.User.USER;
}
